[package]
name = "rtiaw"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[[example]]
name = "genscenes"

[lints.clippy]
pedantic = {level = "deny", priority = -1}
nursery = {level = "deny", priority = -1}
unwrap_used = "deny"

[dependencies]
rand = "0.9.2"
